log_level: info
http:
  address: :8800
  keep_alive: true
db:
  driver: mysql
  database: jenkins
  username: root
  password: Unipal666
  host: 172.168.1.10
  port: 3306
  max_idle_conns: 5
  max_open_conns: 10
  conn_max_lifetime: 3600